server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
<<<<<<< HEAD
          uri: lb://auth-service
=======
          uri: http://localhost:8080
>>>>>>> frontend
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: dialogue-service
<<<<<<< HEAD
          uri: lb://dialogue-service
=======
          uri: http://localhost:8081
>>>>>>> frontend
          predicates:
            - Path=/api/dialogues/**
          filters:
            - StripPrefix=1
        - id: ml-service
<<<<<<< HEAD
          uri: lb://ml-service
=======
          uri: http://localhost:8083
>>>>>>> frontend
          predicates:
            - Path=/api/ml/**
          filters:
            - StripPrefix=1

jwt:
  secret: your-256-bit-secret-key-here-must-be-secure
  expiration: 1h

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.mentor.apigateway: TRACE